server:
  port: 8080

spring:
  application:
    name: phone-recommend-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: sun123456
  sql:
    init:
      mode: always
      encoding: UTF-8
      continue-on-error: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

app:
  jwt-secret: "phoneRecommendSystem2024SecretKeyJavaJwtMinLength32"
  cors-origin: "http://localhost:5173"
